apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: grpc-k8s-headless-client:v2
          imagePullPolicy: Never
          command: ["/app/client"]
          args: ["-addr=dns:///grpc-server-svc:50051"]
