apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: grpc-k8s-headless-server:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          command: ["/app/server"]
          args: ["-host=0.0.0.0"]
