apiVersion: v1
kind: Service
metadata:
  name: grpc-server-svc
spec:
  clusterIP: None  # enable headless service
  selector:
    app: grpc-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
